name: Lobby
version: '1.0-DEV'
description: "The hub plugin for Minebo."
authors: ["Ian Rich"]
website: "https://github.com/MineboMC/Lobby"
main: net.minebo.lobby.Lobby
depend: ["Basalt"]
api-version: '1.20'